FROM golang:1.11.1-alpine
ENV CGO_ENABLED 0

RUN apk add --no-cache --update make git perl-utils dep shadow

ARG CACHE_BUSTER="wat"

ENV PATH "/go/bin:${PATH}"

RUN go get honnef.co/go/tools/cmd/staticcheck

RUN mkdir -p /go/src/github.com/joyent/conch-shell/

ARG BRANCH="master"

WORKDIR /go/src/github.com/joyent/
RUN git clone --branch $BRANCH https://github.com/joyent/conch-shell conch-shell
WORKDIR /go/src/github.com/joyent/conch-shell

ENTRYPOINT ["make" ]
CMD [ "release", "checksums" ]

